### ISSUE TITLE
Request to use your repo for Kubernetes Deployment

### ISSUE THREAD

**Issue by oguzhan-yilmaz** [DazWilkin/crtsh-exporter#16]
Hey, I've created an issue because I couldn't message you anywhere else.

I'd like to use your repo to create a Helm Chart for kubernetes deployment if it's OK with you.

Thanks for the great work!

**Comment by DazWilkin** [comment]
Thanks for connecting and for the feedback.

You're welcome to create a Helm Chart for the repo.

**Comment by oguzhan-yilmaz** [comment]
Thanks for your kindness. I figure out that project exports the expired certs. I'd like to create alarms for soon-to-be-expired certs, so I'm discontinuing my little project. Maybe I'll have to fork this repo or create my own exporter.

Thanks again!

**Comment by DazWilkin** [comment]
I've alerts configured for soon-to-be-expired certs:

```YAML
- alert: certificate_expiry_within_7_days
  expr: sum without(instance,job,serial_number) (crtsh_exporter_certificate_expiry{}) < time()+7*86400
  for: 1h
  labels:
    severity: page
  annotations:
    summary: Certificate ({{ $labels.name }}) expires within 7 days (at {{ $value }} UNIX epoch)
```
